---
name: API Automation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: api_automation

      - name: Run API Tests
        run: npm run test-with-report
        working-directory: api_automation

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: API-Test-Report
          path: api_automation/reports/newman_report.html
