---
name: Playwright UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd ui_automation
          npm install


      - name: Run Playwright Tests
        run: |
          cd ui_automation
          npm run test

      - name: Upload Playwright HTML Report
        if: always()  # ensure condition is true/false (not "Yes" or "No")
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ui_automation/playwright-report/
