---
name: Playwright UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd ui_automation
          npm install
      - name: Print flag if environment variables are set
        run: |
          if [ -z "$LOGIN_URL" ] || [ -z "$ACCOUNT" ]; then
            echo "Environment variables are not set correctly!"
            exit 1  # Fail the job if variables are not set
          else
            echo "Environment variables are set correctly."
              fi

      - name: Run Playwright Tests
        run: |
          cd ui_automation
          npm run test

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ui_automation/playwright-report/

    env:
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      ACCOUNT: ${{ secrets.ACCOUNT }}
      PASSWORD: ${{ secrets.PASSWORD }}
